spring:
  application:
    name: oner-service
  datasource:
    url: jdbc:mysql://localhost:3307/petclinic_msa
    username: user
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true


server:
  port: 8081
